"""
import a Fidelity transaction-history (Accounts -> History -> Download) CSV into
the `transactions` table, and classify each row so we can separate EXTERNAL FLOWS
(money/shares you moved in or out) from internal activity (buys, sells, dividends).

usage:
    python ingest/fidelity_transactions.py data/Accounts_History.csv

once loaded, net additions/withdrawals and true performance become answerable.

NOTE: the classification below keys off Fidelity's free-text "Action" strings,
which vary a bit by account/era. it's a solid first pass — after importing your
file, run `--audit` to see any actions that fell through to 'other' so we can map
them precisely:
    python ingest/fidelity_transactions.py data/Accounts_History.csv --audit
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from portfolio_db import get_connection, init_db  # noqa: E402

COLUMN_ALIASES = {
    "run_date": ["run date", "date"],
    "account_id": ["account number", "account"],
    "action": ["action", "transaction type"],
    "symbol": ["symbol"],
    "description": ["security description", "description"],
    "quantity": ["quantity"],
    "price": ["price", "price ($)"],
    "amount": ["amount", "amount ($)"],
    "settlement_date": ["settlement date"],
}

# map a Fidelity action (uppercased) to (category, is_external_flow).
# ordered: first matching pattern wins. external flows are the ones that change
# the total portfolio because money/shares crossed its boundary.
ACTION_RULES: list[tuple[str, str, int]] = [
    # ── external: money / securities IN ──
    (r"ELECTRONIC FUNDS TRANSFER RECEIVED", "deposit", 1),
    (r"DIRECT DEPOSIT|CHECK RECEIVED|WIRE.*RECEIV|CONTRIBUTION", "deposit", 1),
    (r"TRANSFERRED IN|TRANSFER OF ASSETS|RECEIVED.*TRANSFER|ASSETS RECEIVED", "transfer_in", 1),
    # ── external: money / securities OUT ──
    (r"ELECTRONIC FUNDS TRANSFER PAID", "withdrawal", 1),
    (r"WITHDRAWAL|CHECK PAID|WIRE.*PAID|DISTRIBUTION PAID", "withdrawal", 1),
    (r"TRANSFERRED OUT|ASSETS DELIVERED|DELIVERED OUT", "transfer_out", 1),
    # ── internal: trades (reallocation within the portfolio) ──
    (r"REINVESTMENT|REINVEST", "reinvestment", 0),
    (r"YOU BOUGHT|BOUGHT", "buy", 0),
    (r"YOU SOLD|SOLD|REDEMPTION", "sell", 0),
    # ── internal: income generated by holdings ──
    (r"DIVIDEND", "dividend", 0),
    (r"INTEREST", "interest", 0),
    (r"LONG-TERM CAP GAIN|SHORT-TERM CAP GAIN|CAPITAL GAIN", "capital_gain", 0),
    # ── costs ──
    (r"FEE|EXPENSE|ADVISORY", "fee", 0),
    # ── internal moves between your own accounts (net-zero to total portfolio) ──
    (r"JOURNALED|JOURNAL", "journal", 0),
]


def _norm(c: str) -> str:
    return re.sub(r"\s+", " ", str(c).strip().lower())


def _resolve_columns(df: pd.DataFrame) -> dict[str, str]:
    available = {_norm(c): c for c in df.columns}
    resolved: dict[str, str] = {}
    for field, aliases in COLUMN_ALIASES.items():
        for alias in aliases:
            if alias in available:
                resolved[field] = available[alias]
                break
    return resolved


def _money(value) -> float | None:
    if value is None:
        return None
    s = str(value).strip()
    if s in ("", "--", "n/a", "N/A", "nan"):
        return None
    neg = s.startswith("(") and s.endswith(")")
    s = s.strip("()").replace("$", "").replace(",", "").strip()
    try:
        num = float(s)
    except ValueError:
        return None
    return -num if neg else num


def _to_iso(value) -> str | None:
    if value is None or str(value).strip() in ("", "nan"):
        return None
    s = str(value).strip()
    for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%b-%d-%Y", "%m/%d/%y"):
        try:
            return pd.to_datetime(s, format=fmt).date().isoformat()
        except (ValueError, TypeError):
            continue
    try:
        return pd.to_datetime(s).date().isoformat()
    except (ValueError, TypeError):
        return None


def classify(action: str | None) -> tuple[str, int]:
    a = (action or "").upper()
    for pattern, category, ext in ACTION_RULES:
        if re.search(pattern, a):
            return category, ext
    return "other", 0


def import_csv(csv_path: Path) -> tuple[int, dict[str, int]]:
    df = pd.read_csv(csv_path, dtype=str, skip_blank_lines=True,
                     on_bad_lines="skip", index_col=False)
    df = df.dropna(how="all")
    cols = _resolve_columns(df)

    missing = [f for f in ("run_date", "account_id", "action") if f not in cols]
    if missing:
        raise SystemExit(
            f"missing expected columns {missing} in {csv_path.name}.\n"
            f"columns present: {list(df.columns)}"
        )

    conn = get_connection()
    category_counts: dict[str, int] = {}
    try:
        for _, row in df.iterrows():
            run_date = _to_iso(row.get(cols["run_date"]))
            action = str(row.get(cols["action"], "")).strip() or None
            if run_date is None or not action:
                continue  # disclaimer / blank rows
            account_id = str(row.get(cols["account_id"], "")).strip()
            category, ext = classify(action)
            category_counts[category] = category_counts.get(category, 0) + 1

            sym = str(row.get(cols.get("symbol", ""), "")).strip().rstrip("*") or None
            conn.execute(
                """INSERT OR IGNORE INTO transactions
                       (run_date, account_id, action, category, is_external_flow,
                        symbol, description, quantity, price, amount, settlement_date)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    run_date, account_id, action, category, ext,
                    sym.upper() if sym else None,
                    str(row.get(cols.get("description", ""), "")).strip() or None,
                    _money(row.get(cols.get("quantity", ""))),
                    _money(row.get(cols.get("price", ""))),
                    _money(row.get(cols.get("amount", ""))),
                    _to_iso(row.get(cols.get("settlement_date", ""))),
                ),
            )
        conn.commit()
        total_rows = conn.execute("SELECT COUNT(*) FROM transactions").fetchone()[0]
    finally:
        conn.close()
    return total_rows, category_counts


def main() -> None:
    parser = argparse.ArgumentParser(description="import Fidelity transaction history")
    parser.add_argument("csv_path", type=Path)
    parser.add_argument("--audit", action="store_true",
                        help="after import, list actions classified as 'other' to tune the map")
    args = parser.parse_args()
    if not args.csv_path.exists():
        raise SystemExit(f"file not found: {args.csv_path}")

    init_db()
    total_rows, counts = import_csv(args.csv_path)
    print(f"transactions table now holds {total_rows} rows. category breakdown this import:")
    for cat in sorted(counts, key=lambda c: -counts[c]):
        print(f"  {cat:14} {counts[cat]}")

    if args.audit or counts.get("other"):
        conn = get_connection()
        rows = conn.execute(
            """SELECT DISTINCT action FROM transactions
               WHERE category = 'other' ORDER BY action"""
        ).fetchall()
        conn.close()
        if rows:
            print(f"\n⚠ {len(rows)} unmapped action string(s) classified as 'other' — "
                  f"share these so we can map them:")
            for r in rows[:40]:
                print(f"    {r['action']}")


if __name__ == "__main__":
    main()
